# version: '3.8'

services:
  customer-management:
    image: customer-management:latest
    build:
      context: .
      dockerfile: ./src/services/Customer/Host/Customer.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5000:8080"
    networks:
      - app-network

  notification-management:
    image: notification-management:latest
    build:
      context: .
      dockerfile: ./src/services/Notification/Host/Notification.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5001:8080"
    networks:
      - app-network 

  inventory-management:
    image: inventory-management:latest
    build:
      context: .
      dockerfile: ./src/services/Inventory/Host/Inventory.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5002:8080"
    networks:
      - app-network 

  order-management:
    image: order-management:latest
    build:
      context: .
      dockerfile: ./src/services/Order/Host/Order.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5003:8080"
    networks:
      - app-network 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: customer_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: 
      - postgre-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    volumes: 
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes: 
      - redis-data:/data

networks:
  app-network:
    driver: bridge


volumes:
  postgre-data:
    driver: local
  rabbitmq-data:
    driver: local
  redis-data:
    driver: local

